import org.apache.commons.lang3.StringUtils;

import java.util.HashMap;

public class SMUtils {

  private static HashMap<String, String> REPLACEMENTS;

  static {
    REPLACEMENTS = new HashMap<>();
    REPLACEMENTS.put("GIPUZKOA BASKET", "GIPUZKOA BASKET CLUB");
    REPLACEMENTS.put("VALENCIA BASKET", "VALENCIA BASKET CLUB");
    REPLACEMENTS.put("UCAM MURCIA", "UCAM MURCIA CB");

    REPLACEMENTS.put("SIMONS, BENJAMIN", "SIMONS, BEN");
    REPLACEMENTS.put("TAVARES, W.", "TAVARES, EDY");
    REPLACEMENTS.put("SHENGELIA, T.", "SHENGELIA, TORNIKE");
    REPLACEMENTS.put("CAMPAZZO, FACU", "CAMPAZZO, FACUNDO");
    REPLACEMENTS.put("HUERTAS, M.", "HUERTAS, MARCELINHO");
    REPLACEMENTS.put("EYENGA, C.", "EYENGA, CHRISTIAN");
    REPLACEMENTS.put("BOUNGOU-COLO, N.", "BOUNGOU-COLO, NOBEL");
    REPLACEMENTS.put("SANCHEZ, AL.", "SANCHEZ, ALFONSO");
    REPLACEMENTS.put("GOLUBOVIC, V.", "GOLUBOVIC, VLADIMIR");
    REPLACEMENTS.put("DOORNEKAMP, A.", "DOORNEKAMP, AARON");
    REPLACEMENTS.put("MCKISSIC, S.", "MCKISSIC, SHAQUIELLE");
    REPLACEMENTS.put("CORBACHO, A.", "CORBACHO, ALBERTO");
    REPLACEMENTS.put("TRIGUERO, J.", "TRIGUERO, JUANJO");
    REPLACEMENTS.put("BARREIRO, J.", "BARREIRO, JONATHAN");
    REPLACEMENTS.put("VEZENKOV, A.", "VEZENKOV, ALEKSANDAR");
    REPLACEMENTS.put("VOIGTMANN, J.", "VOIGTMANN, JOHANNES");
    REPLACEMENTS.put("NAVARRO, J.C.", "NAVARRO, JUAN CARLOS");
    REPLACEMENTS.put("MILOSAVLJEVIC, D.", "MILOSAVLJEVIC, DRAGAN");
    REPLACEMENTS.put("GONZALEZ, JOSE M.", "GONZALEZ, CHEMA");
    REPLACEMENTS.put("SAN MIGUEL, R.", "SAN MIGUEL, RODRIGO");
    REPLACEMENTS.put("RANDOLPH, A.", "RANDOLPH, ANTHONY");
    REPLACEMENTS.put("OLASENI, GABRIEL", "OLASENI, GABE");
    REPLACEMENTS.put("CRUZ, FRANCISCO", "CRUZ, PACO");
    REPLACEMENTS.put("DIMITRIJEVIC, N.", "DIMITRIJEVIC, NENAD");
    REPLACEMENTS.put("SOLUADE, MORAYO", "SOLUADE, MO");
    REPLACEMENTS.put("RUOFF, A.", "RUOFF, ALEX");
    REPLACEMENTS.put("TAYLOR, JEFFERY", "TAYLOR, JEFF");
    REPLACEMENTS.put("SANCHEZ, A.", "SANCHEZ, ALFONSO");
    REPLACEMENTS.put("CVETKOVIC, A.", "CVETKOVIC, ALEKSANDAR");
    REPLACEMENTS.put("CANER-MEDLEY,N.", "CANER-MEDLEY, NIK");
    REPLACEMENTS.put("SHENGUEILA, T.", "SHENGELIA, TORNIKE");
    REPLACEMENTS.put("BURJANADZE, B.", "BURJANADZE, BEQA");
    REPLACEMENTS.put("HLINASON, T.", "HLINASON, TRYGGVI");
    REPLACEMENTS.put("NOGUES, JOSE I.", "NOGUES, JOSE IGNACIO");
    REPLACEMENTS.put("LAPROVITTOLA, N.", "LAPROVITTOLA, NICO");
    REPLACEMENTS.put("SULEJMANOVIC, E.", "SULEJMANOVIC, EMIR");
    REPLACEMENTS.put("VASILEIADIS, K.", "VASILEIADIS, KOSTAS");
    REPLACEMENTS.put("MCFADDEN, THADDUS", "MCFADDEN, THAD");
    REPLACEMENTS.put("SEIBUTIS, R.", "SEIBUTIS, RENALDAS");
    REPLACEMENTS.put("KRAVTSOV, V.", "KRAVTSOV, VIACHESLAV");
    REPLACEMENTS.put("BRODZIANSKY, V.", "BRODZIANSKY, VLADIMIR");
    REPLACEMENTS.put("WHITTINGTON, S.", "WHITTINGTON, SHAYNE");
    REPLACEMENTS.put("HERUN, VOLODYMYR", "GERUN, VOLODIMIR");


  }


  public static String normalize(String text) {

    String normalizedText = StringUtils.stripAccents(text).toUpperCase().trim();

    if (REPLACEMENTS.containsKey(normalizedText)) {
      return REPLACEMENTS.get(normalizedText);
    }

    if (normalizedText.equals("SAN EMETERIO")) {
      return "SAN EMETERIO, FERNANDO";
    }

    return normalizedText;
  }
}
